### ISSUE TITLE
mission.endgame needs fixing and a test written

### ISSUE THREAD

**Issue by scrom** [scrom/Experiments#447]
After a (difficult to reach) play test, mission.endgame throws an error:

ERROR! During game tick. (Useraction: "wait"). Error message/stack: ReferenceError: resultString is not defined 
Oct 23 12:15:18 mvta app/web.1:      at Player.self.endGame (/app/js/server/player.js:4951:20) 
Oct 23 12:15:18 mvta app/web.1:      at Mission.self.processReward (/app/js/server/mission.js:253:61) 
Oct 23 12:15:18 mvta app/web.1:      at MissionController.self.processMissionState (/app/js/server/missioncontroller.js:120:40) 
Oct 23 12:15:18 mvta app/web.1:      at MissionController.self.updateMissions (/app/js/server/missioncontroller.js:230:38) 
Oct 23 12:15:18 mvta app/web.1:      at Map.self.updateMissions (/app/js/server/map.js:732:39)

**Comment by scrom** [comment]
fixed and supported with tests
